### PR TITLE
finish the challenge 5

### PR DESCRIPTION
**Pull request by vk-playground**
home page: http://54.169.87.139:3000/
site page: http://54.169.87.139:3000/attraction/10 
booking page: http://54.169.87.139:3000/booking

test account: test@gmail.com
password: 12345678

### CODE REVIEW

**Comment by cwpeng** [comment]
Aspect ratio (長寬比) of your image in booking.html should be the same as original image in any devices.

**Comment by vk-playground** [comment]
Fixed

**Comment by cwpeng** [comment]
I see no fix.

未命名-2

**Comment by vk-playground** [comment]
Checked😅

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
