### PR TITLE
finish Part 2

### PR DESCRIPTION
**Pull request by vk-playground**

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your online URL for testing.

**Comment by vk-playground** [comment]
http://13.214.106.215:3000/

**Comment by cwpeng** [comment]
Your code will load the same data many times when we scroll down to the bottom, shown as screenshot. Fit it and leave comment for me to review again.

未命名-4

**Comment by vk-playground** [comment]
image
hope it is fixed~

**Comment by cwpeng** [comment]
No, nothing changes.

**Comment by vk-playground** [comment]
Fixed again

**Review by cwpeng — APPROVED** [review]
OK. Done.

Suggestion: code block below is better to put in global and do any related changes necessary, you can think more about the difference behind this suggestion.
```
    let paused = false;
    window.onscroll = function () {
      // when the user is at the bottom of the page
      if (((window.innerHeight + window.scrollY) >= document.body.offsetHeight) && !paused) {
        paused = true;
        getData(page, keyword)
          .then(res => { 
            let nextPage = res[0];
            let data = res[1];
            display(nextPage, data);
          });
      }
    }
```

**Pull request merged**
