### PR TITLE
Revert "api"

### PR DESCRIPTION
**Pull request by vk-playground**
This reverts commit e29f28e13387f3b5305d83c1054cba62039ef65a.

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your online testing URLs as describing in weekly guide.

**Comment by vk-playground** [comment]
http://ec2-13-214-106-215.ap-southeast-1.compute.amazonaws.com:3000/
http://ec2-13-214-106-215.ap-southeast-1.compute.amazonaws.com:3000/api/attractions?page=1&keyword=%E6%BA%AB%E6%B3%89
http://ec2-13-214-106-215.ap-southeast-1.compute.amazonaws.com:3000/api/attraction/3

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. page is started from 0, not 1, according to API spec. So there should be something in http://ec2-13-214-106-215.ap-southeast-1.compute.amazonaws.com:3000/api/attractions?page=0&keyword=%E9%A4%A8
2. response data format of http://ec2-13-214-106-215.ap-southeast-1.compute.amazonaws.com:3000/api/attractions?page=1&keyword=%E6%BA%AB%E6%B3%89 is incorrect obviously.
3. use Elastic IP to shorten your hostname in URLs.

Fix issues, create new commits and request me review again.

**Comment by vk-playground** [comment]
http://13.214.106.215:3000/

http://13.214.106.215:3000/api/attraction/2

http://13.214.106.215:3000/api/attractions?page=0&keyword=%E9%A4%A8

**Comment by cwpeng** [comment]
response data format of http://13.214.106.215:3000/api/attractions?page=4 and http://13.214.106.215:3000/api/attractions?page=1&keyword=%E9%A4%A8 are incorrect obviously.

**Comment by vk-playground** [comment]
updated~

**Comment by cwpeng** [comment]
Looks fine for now. But you should resolve conflicts shown in this page, and request me review again from right side in this page.

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should use LIMIT statement in SQL query to do range selection. It's absolutely bad to get all results at once. I mean you should use LIMIT in following SQL queries and change any related code necessory.
```
SELECT id,stitle,CAT2,xbody,address,info,MRT,latitude,longitude,file FROM website.TPtrip WHERE stitle LIKE %s",("%"+keyword+"%")
SELECT id,stitle,CAT2,xbody,address,info,MRT,latitude,longitude,file FROM website.TPtrip
```

Request me review again after you fixed it.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
