### PR TITLE
E-payment system

### PR DESCRIPTION
**Pull request by vk-playground**
http://127.0.0.1:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your online URL for testing.

**Comment by vk-playground** [comment]
@cwpeng 😅 http://54.169.87.139:3000/

**Comment by cwpeng** [comment]
1. You will redirect to 127.0.0.1 after successful ordering. It cannot work online. You should always test online version to make sure everything is all right.
2. We make website for common users. So, check console for information is not acceptable.
3. Credit card inputs style should align with design.

未命名-2
未命名-4

**Comment by vk-playground** [comment]
those three were fixed. Thank you!

image
image

**Comment by cwpeng** [comment]
I cannot connect to your server.

**Comment by vk-playground** [comment]
@cwpeng just reboot the instance and it's okay now

**Comment by cwpeng** [comment]
1. Don't show prime in alert dialog.
2. Remove booking data after successful ordering.

**Comment by vk-playground** [comment]
Revised :) @cwpeng

**Comment by cwpeng** [comment]
1. We show nothing about tech details after ordering, even get prime successful message. You can think what you as a customer experience when you purchase online.
2. I see no changes. After ordering, back to /booking page, we should see no booking there.

**Comment by vk-playground** [comment]
@cwpeng revised the booking page

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
