### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by vk-playground**
http://13.214.106.215:3000/
http://13.214.106.215:3000/attraction/10

### CODE REVIEW

**Comment by cwpeng** [comment]
Your layout exceeds the screen width in 360px width devices.

未命名-8

**Comment by vk-playground** [comment]
@cwpeng fixed:)

**Comment by cwpeng** [comment]
Fixed, but there is new issue: aspect ratio (長寬比) of images should be the same as original image in any devices.

**Comment by vk-playground** [comment]
@cwpeng please have a look again :)

**Comment by cwpeng** [comment]
Should I review this closed pull request?

**Pull request closed without merging**
